[global]
address = "0.0.0.0"
[global.shutdown]
ctrlc = true
force = false
[global.tls]
certs = "C:/Certbot/live/minecraft.themagicdoor.org/fullchain.pem"
key = "C:/Certbot/live/minecraft.themagicdoor.org/privkey.pem"